export const API_URL = "http://localhost:5000/api";
export const specializations = [
  "Alergologie şi imunologie clinică",
  "Anatomie patologică",
  "Anestezie şi terapie intensivă",
  "Boli infecţioase",
  "Cardiologie",
  "Dermatovenerologie",
  "Endocrinologie",
  "Epidemiologie",
  "Farmaceutică",
  "Gastroenterologie",
  "Genetică medicală",
  "Geriatrie și gerontologie",
  "Hematologie",
  "Hepatologie",
  "Igienă",
  "Medicină de familie",
  "Medicină de urgentă",
  "Medicină internă",
  "Medicină sportivă",
  "Nefrologie",
  "Neonatologie",
  "Neurologie",
  "Oncologie medicală",
  "Pediatrie",
  "Pneumologie",
  "Psihiatrie",
  "Radioterapie",
  "Reumatologie",
  "Chirurgie cardiovasculară",
  "Chirurgie generală",
  "Chirurgie orală şi maxilo-facială",
  "Chirurgie pediatrică",
  "Chirurgie plastică",
  "Obstetrică-ginecologie",
  "Oftalmogie",
  "Ortopedie",
  "Urologie",
];
