export const API_URL = "http://localhost:5000/api";
export const specializations = [
  "Alergologie şi imunologie clinică",
  "Anatomie patologică",
  "Anestezie şi terapie intensivă",
  "Boli infecţioase",
  "Cardiologie",
  "Chirurgie cardiovasculară",
  "Chirurgie generală",
  "Chirurgie orală şi maxilo-facială",
  "Chirurgie pediatrică",
  "Chirurgie plastică",
  "Dermatovenerologie",
  "Endocrinologie",
  "Epidemiologie",
  "Farmaceutică",
  "Gastroenterologie",
  "Genetică medicală",
  "Geriatrie și gerontologie",
  "Hematologie",
  "Hepatologie",
  "Igienă",
  "Medicină de familie",
  "Medicină de urgentă",
  "Medicină internă",
  "Medicină sportivă",
  "Nefrologie",
  "Neonatologie",
  "Neurologie",
  "Obstetrică-ginecologie",
  "Oftalmologie",
  "Oncologie medicală",
  "Ortopedie",
  "Pediatrie",
  "Pneumologie",
  "Psihiatrie",
  "Radioterapie",
  "Reumatologie",
  "Urologie",
];

export const monthNames = [
  "Ianuarie",
  "Februarie",
  "Martie",
  "Aprilie",
  "Mai",
  "Iunie",
  "Iulie",
  "August",
  "Septembrie",
  "Octombrie",
  "Noiembrie",
  "Decembrie",
];

export const monthMapping = {
  Ianuarie: "January",
  Februarie: "February",
  Martie: "March",
  Aprilie: "April",
  Mai: "May",
  Iunie: "June",
  Iulie: "July",
  August: "August",
  Septembrie: "September",
  Octombrie: "October",
  Noiembrie: "November",
  Decembrie: "December",
};
